### ISSUE TITLE
Ready-up mode statusicon bug

### ISSUE THREAD

**Issue by kodaniel** [eyza-cod2/zpam3#1]
In ready-up mode the statusicons are buggy. On the picture below you can see that 5 players marked as "non-ready", but in real only there are 3 awating players.

![shot0001](https://user-images.githubusercontent.com/24585704/81121993-43633a00-8f30-11ea-9eae-c2ee21495fe0.jpg)

It is very hard to start a match because we can't see who didn't hit the ready button yet.

**Comment by eyza-cod2** [comment]
Thanks for feedback, will be fixed in next release

**Comment by kodaniel** [comment]
The bug happens when the player is ready and then dies. The statusicon changes back to notready.
If you did not find the bug yet, maybe it is in the following row. Simply an else statement is missing. Also in the `onJoinedTeam(teamName)` function.

https://github.com/eyza-cod2/zpam3/blob/8c9e528ad09be3ce626bcd36463c3cdf180295ae/source/maps/mp/gametypes/_readyup.gsc#L106
