### ISSUE TITLE
Can nades be randomized?

### ISSUE THREAD

**Issue by xyeLz** [eyza-cod2/zpam3#7]
This isn't so much an issue as it is a feature request. Is there a possibility to create a new cvar, something like `throwing_variation` with a boolean where `0` is off and `1` is randomized? `throwing_variation` in this case would refer to the ability to throw set nades. I have a specific need for preventing set nades (similar to CS, Valorant, and other competitive FPS shooters). My goal is to prevent nades from being thrown from a specific position and having them land in the exact same spot every time. Rather, I was wondering if it could be randomized like bullet spray pattern, where the grenade, when thrown, will have slight variations to which direction the nade is thrown, and perhaps even slighter variations in the strength of the throw, much like would be witnessed in real life. I was also wondering if it could be toggleable as mentioned above, so that those who do not desire this feature can disable it?

**Comment by eyza-cod2** [comment]
I think this is not able to make via custom mod. Grenade throwing is hard-coded into the game.
