### ISSUE TITLE
Voting cannot be allowed while using the mod

### ISSUE THREAD

**Issue by toximaxi** [eyza-cod2/zpam3#9]
I had never issues earlier on with allowing voting within the game. I am running a dedicated server using Ubuntu and trying to set the value of 'scr_allow_vote' 'g_allowvote' variables to 1 directly in the server console. 
When I check the GUI after this, the voting is still not allowed, and when I try to call it via callvote command I receive the error message about voting still being not allowed on the server (see screenshot #2).

![image](https://user-images.githubusercontent.com/48560584/111076283-02429b80-84ec-11eb-8567-ddcd3852f3b2.png)

![image](https://user-images.githubusercontent.com/48560584/111076256-dfb08280-84eb-11eb-97ac-b975fea5053b.png)

**Comment by eyza-cod2** [comment]
1. On server side, you have to set g_allowvote 1 to enable voting
2. I found a bug in code - UI element "5. Call Vote" is not correctly updated and stays disabled. (in needed case it can be accessed by pressing 5 key)

I will fix this issue in next release.

Thanks for feedback!

**Comment by toximaxi** [comment]
Hello,

thank You for the reply. I am able to initiate voting with workaround you described.
Should I close the issue or would you prefer keeping it open until next release?

Regards,
Toxi

**Comment by eyza-cod2** [comment]
Fixed in 3.20
